### PR TITLE
:bug: fix document best practice typo and optimize display style

### LINKED ISSUE #378: 文档最佳实践页面文字有误，Governance 应该为 Contributing
### Describe the bug

image
image

### Steps to reproduce

_No response_

### Logs

_No response_

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by muclover**
fix document best practice typo and optimize display style
fix #378

### CODE REVIEW

File: packages/shared-components/components/software-details/SoftwareDetails.vue [hunk 1]
```diff
@@ -178,7 +178,7 @@ watchEffect(async () => {
         has: data.document?.hasChangelog,
       },
       {
-        title: 'Governance',
+        title: 'Contributing',
         content:
           'Document that explains how the governance and committer process works in the repository.',
```
Comment (flyfishzy) [inline packages/shared-components/components/software-details/SoftwareDetails.vue]: 描述是否正确？

Comment (muclover) [reply packages/shared-components/components/software-details/SoftwareDetails.vue]: 修改了
