### PR TITLE
Fix issues with project dependencies

### LINKED ISSUE #481: vue3被vue3使用，这个使用关系不正确；使用关系从依赖清单获取，依赖关系得优化
### Describe the bug

vue3被vue3使用，这个使用关系不正确；使用关系从依赖清单获取，依赖关系得优化
6eedbd47e22bb7a4f492513ce0450e7

### Steps to reproduce

_No response_

### Logs

_No response_

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by WilliamHeaven**
close #481

### CODE REVIEW

File: packages/integration/controllers/projectDependencies.js [hunk 1]
```diff
@@ -87,39 +84,75 @@ export async function getDependencies(project, seen) {
...
   });
   if (dependenciesData === undefined || !dependenciesData['repository']) {
     return;
   }
-  const dependenciesList = await parseDependenciesData(project, dependenciesData, seen);
-  await saveDate(dependenciesList);
+  const dependData = await parseDependenciesData(project, dependenciesData, seen);
+  await softDeleteDependencies(project, dependData.dependFullNameList);
+  await saveDate(dependData.dependenciesList);
+  await sleep(3000);
```
Comment (flyfishzy) [inline packages/integration/controllers/projectDependencies.js]: ?

Comment (flyfishzy) [inline packages/integration/controllers/projectDependencies.js]: ？
